[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytest-markdown-report"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = []
authors = [
    { name = "Vladimir Petrigo", email = "vladimir.petrigo@gmail.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Framework :: Pytest",
]
dependencies = [
    "pytest>=7",
    "py-markdown-table~=1.3",
]

[project.entry-points.pytest11]
pytest_markdown_report = "pytest_markdown_report.plugin"

[project.urls]
Documentation = "https://github.com/Vladimir Petrigo/pytest-markdown-report#readme"
Issues = "https://github.com/Vladimir Petrigo/pytest-markdown-report/issues"
Source = "https://github.com/Vladimir Petrigo/pytest-markdown-report"

[tool.hatch.version]
path = "src/pytest_markdown_report/__about__.py"

[tool.hatch.env]
requires = [
    "hatch-pip-compile"
]

[tool.hatch.envs.default]
installer = "uv"
type = "pip-compile"
pip-compile-resolver = "uv"
pip-compile-installer = "uv"

[tool.hatch.envs.types]
extra-dependencies = [
    "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/pytest_markdown_report tests}"

[tool.hatch.envs.test]
installer = "uv"
type = "pip-compile"
pip-compile-resolver = "uv"
pip-compile-installer = "uv"

[tool.hatch.envs.test.scripts]
run = "pytest {args:tests}"

[[tool.hatch.envs.test.matrix]]
python = ["3.11", "3.12", "3.13", "3.14"]
pytest = ["7", "8", "9"]

[tool.hatch.envs.test.overrides]
matrix.pytest.dependencies = [
    { value = "pytest>=7,<8", if = ["7"] },
    { value = "pytest>=8,<9", if = ["8"] },
    { value = "pytest>=9,<10", if = ["9"] },
]

[tool.coverage.run]
source_pkgs = ["pytest_markdown_report", "tests"]
branch = true
parallel = true
omit = [
    "src/pytest_markdown_report/__about__.py",
]

[tool.coverage.paths]
pytest_markdown_report = ["src/pytest_markdown_report", "*/pytest-markdown-report/src/pytest_markdown_report"]
tests = ["tests", "*/pytest-markdown-report/tests"]

[tool.coverage.report]
exclude_lines = [
    "no cov",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
