[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytest-markdown-summary"
dynamic = ["version"]
description = 'A Pytest plugin for generating reports in Markdown format.'
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = [
    "pytest", "plugin", "markdown"
]
authors = [
    { name = "Vladimir Petrigo", email = "vladimir.petrigo@gmail.com" },
]
classifiers = [
    "Environment :: Plugins",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Framework :: Pytest",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
    "Topic :: Text Processing",
    "Topic :: Text Processing :: Markup :: Markdown",
    "Typing :: Typed",
]
dependencies = [
    "pytest>=7,<10",
    "py-markdown-table~=1.3",
]

[project.entry-points.pytest11]
pytest_markdown_summary = "pytest_markdown_summary.plugin"

[project.urls]
Documentation = "https://github.com/vpetrigo/pytest-markdown-summary#readme"
Issues = "https://github.com/vpetrigo/pytest-markdown-summary/issues"
Source = "https://github.com/vpetrigo/pytest-markdown-summary"

[tool.hatch.version]
path = "src/pytest_markdown_summary/__about__.py"

[tool.hatch.env]
requires = [
    "hatch-pip-compile"
]

[tool.hatch.build.targets.sdist]
exclude = [
    "/.github",
    "/requirements",
]

[tool.hatch.envs.default]
installer = "uv"
type = "pip-compile"
pip-compile-resolver = "uv"
pip-compile-installer = "uv"

[tool.hatch.envs.types]
extra-dependencies = [
    "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/pytest_markdown_summary tests}"

[tool.hatch.envs.test]
installer = "uv"
type = "pip-compile"
pip-compile-resolver = "uv"
pip-compile-installer = "uv"

[tool.hatch.envs.test.scripts]
run = "pytest {args:tests}"

[[tool.hatch.envs.test.matrix]]
python = ["3.11", "3.12", "3.13", "3.14"]
pytest = ["7", "8", "9"]

[tool.hatch.envs.test.overrides]
matrix.pytest.dependencies = [
    { value = "pytest>=7,<8", if = ["7"] },
    { value = "pytest>=8,<9", if = ["8"] },
    { value = "pytest>=9,<10", if = ["9"] },
]

[tool.coverage.run]
source_pkgs = ["pytest_markdown_summary", "tests"]
branch = true
parallel = true
omit = [
    "src/pytest_markdown_summary/__about__.py",
]

[tool.coverage.paths]
pytest_markdown_summary = ["src/pytest_markdown_summary", "*/pytest-markdown-summary/src/pytest_markdown_summary"]
tests = ["tests", "*/pytest-markdown-summary/tests"]

[tool.coverage.report]
exclude_lines = [
    "no cov",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
