name: CI

on:
  push:
  pull_request:
  workflow_call:
  schedule:
    - cron: "0 0 * * 3"

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Install Hatch
        run: uv tool install "git+https://github.com/vpetrigo/hatch@fix/hardcoded-reliance-on-pip"

      - name: Run linting
        run: hatch fmt -l --check

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Install Hatch
        run: uv tool install "git+https://github.com/vpetrigo/hatch@fix/hardcoded-reliance-on-pip"

      - name: Run format check
        run: hatch fmt -f --check

  test:
    name: Test - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Install Hatch
        run: uv tool install "git+https://github.com/vpetrigo/hatch@fix/hardcoded-reliance-on-pip" --with hatch-pip-compile

      - name: Run tests
        run: hatch run +py=${{ matrix.python-version }} test:run
